### ISSUE TITLE
setImageHttp is not a function

### ISSUE THREAD

**Issue by gk611995** [fbsanches/cordova-plugin-wallpaper#24]
Hello,

Tried this plugin but doesn't seem to work.I am trying to set an image from remote location as wallpaper.
It gives this error `window.plugins.wallpaper.setImageHttp is not a function
    at a.setwallpaper (file:///android_asset/www/js/0.cf0735399bc2e4f4f677.js:1:510)
    at a.n [as setwallpaper] (file:///android_asset/www/js/vendor.js:1:1143)
    at a.created (file:///android_asset/www/js/0.cf0735399bc2e4f4f677.js:1:660)
    at Dt (file:///android_asset/www/js/vendor.js:1:12637)
    at a.t._init (file:///android_asset/www/js/vendor.js:6:7891)
    at new a (file:///android_asset/www/js/vendor.js:1:22033)
    at _e (file:///android_asset/www/js/vendor.js:1:18964)
    at init (file:///android_asset/www/js/vendor.js:6:7148)
    at c (file:///android_asset/www/js/vendor.js:6:16698)
    at l (file:///android_asset/www/js/vendor.js:6:16327)`

**Comment by vaibhav2110** [comment]
Having exact same problem.

**Comment by gk611995** [comment]
Wrote a plugin myself

**Comment by vaibhav2110** [comment]
Can you tell me what you did or share your work , please?

**Comment by gk611995** [comment]
Check my repo

**Comment by vaibhav2110** [comment]
Hey, can you tell how to add that plugin because "ionic cordova plugin add https://github.com/gk611995/WallpaperPlugin.git" is not working and If I add it manually in plugins folder, update the config.xml and then use it in my page.ts nothing happens. Sorry I am new to all these, please add how to use it.

**Comment by gk611995** [comment]
Can u give me your email ID

**Comment by vaibhav2110** [comment]
here: vaibhpraky@gmail.com

**Comment by yaswanthkata** [comment]
Hi ,
I'm too trying hard to work with it.please send me how to use your repo.
Thanks a ton in advance

On 21-Jan-2018 4:25 PM, "vaibhav2110" <notifications@github.com> wrote:

here: vaibhpraky@gmail.com

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fbsanches/cordova-plugin-wallpaper/issues/24#issuecomment-359239595>,
or mute the thread

**Comment by Fieel** [comment]
This whole thread is annoying. I was looking for a solution but instead found this, a bunch of guys sharing stuff through e-mail instead of posting a solution here  :/.

My workaround, waiting for a solution:
SetImageHttp is not a function so i downloaded the image as blob, used the Base64 Ionic plugin and converted the downloaded image to a string and set it as wallpaper using the SetImageBase64 which takes a Base64 string as input. Not elegant but works for now.
